### ISSUE TITLE
Sidebar not displaying properly

### ISSUE THREAD

**Issue by katiemma** [FairSparkBooks/ComicCollabPublic#13]
![Screenshot 2020-04-30 at 15 48 17](https://user-images.githubusercontent.com/64597973/80724776-224ab580-8afa-11ea-8fa8-ac3f84dce557.png)

**Comment by katiemma** [comment]
When project was first created after first time logging in this wasn't an issue. However after creating project, logging out then logging back in the side bar wasn't displaying properly and appears "cut off".

Seems to work again after refreshing a few times.

**Comment by ageddesi** [comment]
This is now fixed, the state is stored locally so will be remembered next time you login unless you clear your local storage.
