### ISSUE TITLE
Edit project task board

### ISSUE THREAD

**Issue by katiemma** [FairSparkBooks/ComicCollabPublic#16]
In the board settings could there be a way to re-arrange order of board categories?

I.e from script, pencils inks, option to change manually change to inks, pencils, script. Or perhaps a function to organise automatically: alphabetically, date created etc.

![Screenshot 2020-04-30 at 16 11 12](https://user-images.githubusercontent.com/64597973/80727134-3cd25e00-8afd-11ea-9696-94757cc548fb.png)

**Comment by katiemma** [comment]
Also the "Add New" button aesthetically looks a little bit too high up?

**Comment by ageddesi** [comment]
#31 - Created ticket to track category name editing

**Comment by ageddesi** [comment]
#Re-order #32  - Created ticket to track re-ordering of categories.
