### ISSUE TITLE
Project view - include available actions

### ISSUE THREAD

**Issue by nocturnalmonkey** [FairSparkBooks/ComicCollabPublic#43]
<img width="1346" alt="Screenshot 2020-05-03 at 10 31 45" src="https://user-images.githubusercontent.com/832227/80910741-78ea0680-8d29-11ea-819b-9e1d3a6747e2.png">

From the Dashboard, I clicked "View project" and hit the screen above. At the moment, this is a bit of a dead end. Perhaps add some entry-points here for Tasks, Scripts, Artworek etc

**Comment by ageddesi** [comment]
We are hoping to build this page out to give a better overview of the project. current issues in progress. latest artwork uploaded, this kind of stuff, but adding some action buttons for doing stuff is a good idea for the moment. :)

**Comment by ageddesi** [comment]
![image](https://user-images.githubusercontent.com/1301564/80913090-ca9a8d00-8d39-11ea-95ff-3a3fd09bc00e.png)
