### ISSUE TITLE
ok i have made some tasks in script and have written a short script... now what?

### ISSUE THREAD

**Issue by anim8or** [FairSparkBooks/ComicCollabPublic#50]
you can assign a task to a user but then you cant flag it as being in, in progress, closed, reopened . indeed as i can seemingly have multiple scripts in a project, how do i link any given script task to a script in the project?  also how do i delete tasks?

**Comment by ageddesi** [comment]
Hey @anim8or thanks for the ticket.

The current design is that you create tickets and they can be moved across the columns by dragging them. There is a done column you can use at the moment by default. 

All tickets will be visible forever but we are looking to add an archive button in that hides them from the board. 

You can also customize the columns that the tickets sit on by clicking on the board settings button in the top right.

![image](https://user-images.githubusercontent.com/1301564/82255807-2e81a000-994d-11ea-9e39-00c3bca365e3.png)

![image](https://user-images.githubusercontent.com/1301564/82255828-3b9e8f00-994d-11ea-8e2e-773cfe6e1cbf.png)

To delete a ticket will be re-added in the next release :) Thank you again for the feedback and hope this helps

-
