### ISSUE TITLE
Error message for password not meeting requirements is not formatted correctly

### ISSUE THREAD

**Issue by kbhasi** [FairSparkBooks/ComicCollabPublic#58]
I tested this on the "dev" server, and in both Pale Moon and Firefox _(I assume the lead developer is only testing on Chrome, but I may be wrong)_.

The error message for passwords not metting requirements isn't formatted correctly (each letter is in its own message box(?), rather than just one) and thus the password rules aren't clear, but I figured them out after a few minutes. To reproduce this issue, just attempt to create an account with a password less than 6 characters long.

![image](https://user-images.githubusercontent.com/37286461/82600271-3dcc4c00-9be0-11ea-948c-c5ff756fcf82.png)

**Comment by ageddesi** [comment]
Thanks for raising this. We will sort this out in the next release.

**Comment by ageddesi** [comment]
![SmartSelect_20200521-211856_Chrome](https://user-images.githubusercontent.com/1301564/82602340-d7780700-9ba8-11ea-9d81-c055c3847f20.jpg)

Need to handle this exception
